### ISSUE TITLE
touch is not working when session.cookie.expires is not set

### ISSUE THREAD

**Issue by vicneanschi** [rawberg/connect-sqlite3#11]
The code for touch() is not calling the callback which express-session is expecting.
This code is going to be triggered when session is set with {resave: false} option.

**Comment by vedran-maestral** [comment]
Is this related?

http://stackoverflow.com/questions/34589378/using-sqlite-in-express-session

**Comment by rawberg** [comment]
its possible, however the code in the SO post has resave set to true.

**Comment by drfloob** [comment]
More than just `touch` not working, this bug prevents the last bit of data from being sent. The first request goes fine (before the cookie is established). But on all subsequent requests, the browser hangs, and eventually times out with an `ERR_CONTENT_LENGTH_MISMATCH` error, having received a partial response. Here's a min-repro for the problem: https://gist.github.com/drfloob/ad827c5f575720ce518d

I've got a pull request coming in a moment that fixes this. But just in case, setting a `maxAge` on the cookie is a workaround, as so is setting `resave: true` (or leaving it true by default) in the config as vicneanschi said.

**Comment by vicneanschi** [comment]
Thanks for fixing this!
