### ISSUE TITLE
Creating the directory for database file, if it does not exists

### ISSUE THREAD

**Issue by Apkovy** [rawberg/connect-sqlite3#29]
I migrated from session-file-store to connect-sqlite3 store. 

What I am really missing is the feature, when the directory from `dir `option is created, if it did not exist already.

I checked the file-store code and they are using the `fsExtra.mkdirsSync` method to create even the nested path along the way, if it does not exists.

Thanks!

**Comment by rawberg** [comment]
If you'd like to put together a PR I'd be happy to review and merge it.

**Comment by Apkovy** [comment]
Thank you.

I create PR #30 and tested in my environment for both single non-existing directory and recursively for non-existing(or partially existing) directory path inside th
